### ISSUE TITLE
Fix CORS issues

### ISSUE THREAD

**Issue by beaufortfrancois** [GoogleChrome/kino#152]
As raised by DevTools, https://storage.googleapis.com/kino-assets/ files should have should `Access-Control-Allow-Origin` header set.

`Access to fetch at 'https://storage.googleapis.com/kino-assets/streaming-basics/thumbnail.png' from origin 'https://kinoweb.dev' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`
`Access to fetch at 'https://storage.googleapis.com/kino-assets/single-video/thumbnail.png' from origin 'https://kinoweb.dev' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`
`Uncaught (in promise) TypeError: Failed to fetch precacheAssets @ sw.js:651`

**Comment by beaufortfrancois** [comment]
I think it applies to all files listed in https://github.com/GoogleChrome/kino/blob/05cb0f56bc31a589a33a0c4e979344208e17ef52/src/js/sw/cache.js#L34-L39

**Comment by beaufortfrancois** [comment]
@derekherman @dero Can you have a look at this issue?

**Comment by derekherman** [comment]
@beaufortfrancois We were looking at this yesterday and seeing some odd behavior during SW registration. I think @dero said he was going to look into it some more but not sure if he’s gotten to it yet.

**Comment by dero** [comment]
@beaufortfrancois @derekherman I was able to confirm the issue earlier. Then we re-ran the script that sets CORS headers on the static bucket items.

I've since re-checked the issue and the bottom line is that the issue seems now resolved after the recent re-run of the CORS script.

I've unregistered the SW and let it re-cache all static items and then checked the response headers for the bucket items. The `origin` request header is properly sent and the `access-control-allow-origin` response header is returned as expected with the correct value.

![image](https://user-images.githubusercontent.com/433570/133973015-5ca36bbe-69f2-4729-bbd4-4e89d7d6d9c3.png)

I tested everything using `curl`, just for good measure:

```
curl https://storage.googleapis.com/kino-assets/streaming-basics/thumbnail.png --header "Origin: https://kinoweb.dev" --dump-header headers.txt > /dev/null
```

And the returned headers again contained the expected `access-control-allow-origin`:

```
HTTP/2 200
x-guploader-uploadid: ADPycdsj-0EfRilYsL6s0lFT9kYdOpUOC6sMHlSS8XDZk2syXLv8Ss3MRrAmy9hoOAfxLfHtZXFEk7omu9uZ8_zqKS0hcLa2lA
expires: Mon, 20 Sep 2021 09:06:45 GMT
date: Mon, 20 Sep 2021 08:06:45 GMT
last-modified: Sun, 23 May 2021 00:42:24 GMT
etag: "733b52179f4df28c3d45d111668cec49"
x-goog-generation: 1621730544499387
x-goog-metageneration: 1
x-goog-stored-content-encoding: identity
x-goog-stored-content-length: 66782
content-type: image/png
x-goog-hash: crc32c=ezuiZg==
x-goog-hash: md5=cztSF59N8ow9RdERZozsSQ==
x-goog-storage-class: STANDARD
accept-ranges: bytes
content-length: 66782
access-control-allow-origin: https://kinoweb.dev
access-control-expose-headers: Accept-Ranges, Content-Length, Content-Type, Date, Origin, Range, Server, Transfer-Encoding, X-GUploader-UploadID, X-Google-Trace
vary: Origin
server: UploadServer
cache-control: public, max-age=3600
age: 0
alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
```

Unless we can reproduce the issue, I don't see how

**Comment by beaufortfrancois** [comment]
Perfect. Thank you! You can close this issue.
